# ------------------------
# General App Config
# ------------------------
app:
  host-url: http://localhost:8080
  test-mail: cgjirafinal@gmail.com
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

# ------------------------
# Spring Boot Config
# ------------------------
spring:
  profiles:
    active: test
  config:
    import: "optional:classpath:secrets.properties"

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20

  datasource:
    url: jdbc:postgresql://localhost:5435/jira
    username: ${db.username}
    password: ${db.password}

  liquibase:
    enabled: false
  sql:
    init:
      mode: always

  cache:
    cache-names: users
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=5m

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${oauth.github.client-id}
            client-secret: ${oauth.github.client-secret}
            scope:
              - email
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            scope:
              - email
              - profile
          facebook:
            client-id: ${oauth.facebook.client-id}
            client-secret: ${oauth.facebook.client-secret}
            scope: email
          gitlab:
            client-id: ${oauth.gitlab.client-id}
            client-secret: ${oauth.gitlab.client-secret}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          facebook:
            authorization-uri: https://graph.facebook.com/oauth/authorize
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me
            user-name-attribute: response
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  thymeleaf:
    check-template-location: false

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

# ------------------------
# Logging
# ------------------------
logging:
  level:
    root: WARN
    com.codegym.jira: DEBUG
    com.codegym.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

# ------------------------
# Server
# ------------------------
server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ------------------------
# SpringDoc OpenAPI
# ------------------------
springdoc:
  swagger-ui:
    path: /doc